server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  accessLogEnabled: true
#  serverRoot: /Users/zze/Work/code/github/devops-helper/resource/dist
#  indexFiles: [ "index.html", "main.html" ]


logger:
  level: "all"
  stdout: true

database:
  logger:
    level: "all"
    stdout: "true"
  default:
    type: mysql
    link: "mysql:devops_super:devops_super.zze@tcp(192.168.2.231:3306)/devops_super?loc=Local&parseTime=true"
    charset: utf8mb4
    maxIdle: "10"
    maxOpen: "300"
    debug: true

jwt:
  secret: vIIEngfamGZasdkseadgF9fe
  expire: 8h

host:
  terminal:
    sessionFileDir: host-sessions
