
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - registry-azj-registry.cn-shanghai.cr.aliyuncs.com/ops/
  gen:
    dao:
      - link: "mysql:devops_super:devops_super.zze@tcp(192.168.2.231:3306)/devops_super?loc=Local&parseTime=true"
        group: default
        tables: "user, permission, role, dept, host, host_group, host_terminal_session, kubernetes_config, ci_env, ci_pipeline"
        withTime: false
        gJsonSupport: true
        overwriteDao: true
        descriptionTag: true
#        jsonCase: Snake
        clear: true